CREATE TYPE "contatos" AS ENUM (
  'CELULAR',
  'EMAIL',
  'WHASTAPP'
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(50) NOT NULL,
  "saldo" decimal(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE "contato" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_contato" contatos NOT NULL,
  "cliente_id" integer NOT NULL,
  "informacao" varchar(50) NOT NULL
);

CREATE TABLE "carro" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "placa" char(7) NOT NULL,
  "modelo" varchar(20)
);

CREATE TABLE "cliente_carro" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cliente_id" integer NOT NULL,
  "carro_id" integer NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "tipo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao" varchar(20) NOT NULL,
  "valor" decimal(10,2)
);

CREATE TABLE "vaga" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero" char(3) NOT NULL,
  "tipo_id" integer NOT NULL
);

CREATE TABLE "estacionamento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cliente_carro_id" integer NOT NULL,
  "vaga_id" integer NOT NULL,
  "entrada" timestamp NOT NULL,
  "saida" timestamp NOT NULL
);

CREATE UNIQUE INDEX "uk_cliente_tipo" ON "contato" ("tipo_contato", "cliente_id");

CREATE UNIQUE INDEX "uk_placa" ON "carro" ("placa");

CREATE UNIQUE INDEX "uk_cliente_carro" ON "cliente_carro" ("cliente_id", "carro_id");

CREATE UNIQUE INDEX "uk_vaga_tipo" ON "vaga" ("numero");

CREATE UNIQUE INDEX "uk_estacionamento" ON "estacionamento" ("cliente_carro_id", "vaga_id", "entrada");

ALTER TABLE "contato" ADD CONSTRAINT "fk_contato_cliente" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cliente_carro" ADD CONSTRAINT "fk_cliente_carro_cliente" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cliente_carro" ADD CONSTRAINT "fk_cliente_carro_carro" FOREIGN KEY ("carro_id") REFERENCES "carro" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estacionamento" ADD CONSTRAINT "fk_estacionamento_cliente_carro" FOREIGN KEY ("cliente_carro_id") REFERENCES "cliente_carro" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estacionamento" ADD CONSTRAINT "fk_estacionamento_vaga" FOREIGN KEY ("vaga_id") REFERENCES "vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga" ADD CONSTRAINT "fk_vaga_tipo" FOREIGN KEY ("tipo_id") REFERENCES "tipo" ("id") DEFERRABLE INITIALLY IMMEDIATE;
