CREATE TYPE "tipo_contato" AS ENUM (
  'CELULAR',
  'EMAIL',
  'WHATSAPP'
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cpf" char(11) NOT NULL,
  "nome" varchar(50) NOT NULL
);

CREATE TABLE "contato" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cliente_id" char(11) NOT NULL,
  "tipo" tipo_contato NOT NULL,
  "informacao" varchar(50) NOT NULL
);

CREATE TABLE "item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "encomenda_id" integer NOT NULL,
  "placa_id" integer NOT NULL,
  "frase" varchar(30) NOT NULL,
  "quantidade" integer NOT NULL,
  "cor_fundo_id" integer NOT NULL,
  "cor_frase_id" integer NOT NULL
);

CREATE TABLE "encomenda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "data_pedido" date NOT NULL,
  "entrega" date NOT NULL,
  "cliente_id" integer NOT NULL,
  "desconto_id" integer NOT NULL
);

CREATE TABLE "placa" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "altura" integer NOT NULL,
  "largura" integer NOT NULL,
  "material_id" integer NOT NULL
);

CREATE TABLE "desconto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "percentual" decimal(10,2) NOT NULL,
  "valor_minimo" decimal(10,2) NOT NULL,
  "valor_maximo" decimal(10,2) NOT NULL
);

CREATE TABLE "cor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao" varchar(20) NOT NULL,
  "fundo" boolean NOT NULL,
  "letra" boolean NOT NULL
);

CREATE TABLE "material" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao" varchar(20) NOT NULL,
  "valor_letra" decimal(10,2) NOT NULL,
  "custo" decimal(10,2) NOT NULL
);

CREATE UNIQUE INDEX "uk_cpf" ON "cliente" ("cpf");

CREATE UNIQUE INDEX "uk_contato" ON "contato" ("cliente_id", "tipo");

ALTER TABLE "encomenda" ADD CONSTRAINT "fk_encomenda_desconto" FOREIGN KEY ("desconto_id") REFERENCES "desconto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_cor_fundo" FOREIGN KEY ("cor_fundo_id") REFERENCES "cor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_cor_frase" FOREIGN KEY ("cor_frase_id") REFERENCES "cor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "placa" ADD CONSTRAINT "fk_placa_material" FOREIGN KEY ("material_id") REFERENCES "material" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contato" ADD CONSTRAINT "fk_contato_cliente" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "encomenda" ADD CONSTRAINT "fk_encomenda_cliente" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_encomenda" FOREIGN KEY ("encomenda_id") REFERENCES "encomenda" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_placa" FOREIGN KEY ("placa_id") REFERENCES "placa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

/*-----------------------------------------------------------------------------------------------------------*/
CREATE TYPE situacao_encomenda AS ENUM (
  'Aberta',
  'Fechada'
);

ALTER TABLE encomenda ADD valor decimal(10,2) NOT NULL, valor_sinal decimal(10,2) NOT NULL;
ALTER TABLE encomenda
  DROP COLUMN desconto_id;
ALTER TABLE encomenda ADD situacao situacao_encomenda NOT NULL DEFAULT 'Aberta';

CREATE TABLE recebimento (
  id_recebimento SERIAL PRIMARY KEY,
  id_encomenda INTEGER NOT NULL,
  valor_pago DECIMAL (10,2) NOT NULL,
  data_pagamento DATE,

  CONSTRAINT fk_recebimento_valor
    FOREIGN KEY (id_encomenda)
    REFERENCES encomenda(id)
);

DROP TABLE IF EXISTS desconto;
/*-----------------------------------------------------------------------------------------------------------*/
INSERT INTO cliente (cpf,nome)
VALUES 
  ('01236547899','Jailson Mendes'),
  ('14259763120','Luva de Pedreiro'), 
  ('47157466321','Goku'),
  ('00145778557','Neymar Jr'),
  ('98689120255','Dom Pedro I');

INSERT INTO cor (descricao,fundo,letra)
VALUES 
  ('branca',True,False),
  ('cinza',True,False),
  ('azul',False,True),
  ('verde',False,True),
  ('amarelo',False,True),
  ('preto',False,True),
  ('vermelho',False,True),
  ('roxo',False,True);
/*fundo = branca e cinza*/
/*letra = azul,verde,amarela,preto,vermelho*/
INSERT INTO material (descricao,valor_letra, custo)
VALUES
  ('madeira',1.50,3.0),  /*1*/
  ('aço',5.50,5.50),     /*2*/
  ('plástico',3.50,2.0); /*3*/

INSERT INTO placa (altura,largura,material_id)
VALUES
  (8,15,1),
  (30,45,1),
  (10,14,3),
  (15,10,2),
  (20,30,3);

INSERT INTO encomenda (data_pedido,entrega,cliente_id,valor,valor_sinal,situacao)
VALUES
  ('2024-01-05','2024-01-15',1,180.00,90.00,'Fechada'),
  ('2024-01-08','2024-01-18',2,320.00,160.00,'Fechada'),
  ('2024-01-12','2024-01-22',3, 95.00, 47.50,'Fechada'),
  ('2024-01-15','2024-01-25',4,410.00,205.00,'Fechada'),
  ('2024-01-20','2024-01-30',5,150.00, 75.00,'Fechada'),
  ('2024-01-25','2024-02-04',1,275.00,137.50,'Fechada'),
  ('2024-02-01','2024-02-11',2,500.00,250.00,'Fechada'),
  ('2024-02-05','2024-02-15',3,120.00, 60.00,'Fechada'),
  ('2024-02-10','2024-02-20',4,340.00,170.00,'Fechada'),
  ('2024-02-14','2024-02-24',5,210.00,105.00,'Fechada'),
  ('2024-02-18','2024-02-28',1,160.00, 80.00,'Aberta'),
  ('2024-02-22','2024-03-04',2,290.00,145.00,'Aberta'),
  ('2024-02-25','2024-03-07',3,380.00,190.00,'Aberta'),
  ('2024-03-01','2024-03-11',4,100.00, 50.00,'Aberta'),
  ('2024-03-05','2024-03-15',5,450.00,225.00,'Aberta'),
  ('2024-03-08','2024-03-18',1,230.00,115.00,'Aberta'),
  ('2024-03-12','2024-03-22',2,170.00, 85.00,'Aberta'),
  ('2024-03-15','2024-03-25',3,310.00,155.00,'Aberta'),
  ('2024-03-18','2024-03-28',4,260.00,130.00,'Aberta'),
  ('2024-03-22','2024-04-01',5,140.00, 70.00,'Aberta');

INSERT INTO item (encomenda_id,placa_id,frase,quantidade,cor_fundo_id,cor_frase_id)
VALUES
  (1,1,'Bem-vindo',1,1,3),
  (1,2,'Cuidado com o cão',1,2,6),
  (1,3,'Aberto',2,1,7),
  (2,4,'Loja Fechada',1,2,4),
  (2,1,'Vagas Disponiveis',1,1,3),
  (2,5,'Estacionamento Proibido',1,2,7),
  (3,2,'Promoção',1,1,5),
  (3,3,'Sale 50%',1,2,3),
  (3,1,'Atendimento 24h',1,1,6),
  (4,4,'Em Reforma',1,2,7),
  (4,5,'Não Pise na Grama',1,1,4),
  (4,2,'Saída de Emergência',1,2,7),
  (5,1,'Recém-Casados',1,1,3),
  (5,3,'Feliz Aniversário',1,2,8),
  (5,4,'Parabéns',1,1,5),
  (6,5,'Boas Festas',1,2,7),
  (6,1,'Bem-vindo ao Lar',1,1,3),
  (6,2,'Cuidado Cão Bravo',1,2,6),
  (7,3,'Açougue do João',1,1,7),
  (7,4,'Padaria Estrela',1,2,4),
  (7,5,'Mercadinho Bom Preço',1,1,3),
  (8,1,'Salão de Beleza',1,2,8),
  (8,2,'Barbearia Top',1,1,6),
  (8,3,'Pet Shop Amigo',1,2,5),
  (9,4,'Auto Peças Silva',1,1,7),
  (9,5,'Borracharia 24h',1,2,6),
  (9,1,'Lava Rápido',1,1,3),
  (10,2,'Farmácia Popular',1,2,4),
  (10,3,'Clínica Vida',1,1,7),
  (10,4,'Consultório Médico',1,2,3),
  (11,5,'Loja de Roupas',1,1,5),
  (11,1,'Sapataria Bela',1,2,6),
  (12,2,'Restaurante Sabor',1,1,7),
  (12,3,'Pizzaria Forno',1,2,3),
  (13,4,'Sorveteria Doce',1,1,4),
  (13,5,'Cafeteria Aroma',1,2,6),
  (14,1,'Livraria Saber',1,1,7),
  (14,2,'Papelaria Escolar',1,2,5),
  (15,3,'Academia Força',1,1,3),
  (15,4,'Studio de Dança',1,2,7),
  (16,5,'Imobiliária Lar',1,1,4),
  (16,1,'Construtora Forte',1,2,6),
  (17,2,'Material de Construção',1,1,5),
  (17,3,'Vidraçaria Cristal',1,2,7),
  (18,4,'Marcenaria Bom Madeiro',1,1,3),
  (18,5,'Serralheria Aço Forte',1,2,4),
  (19,1,'Eletricista 24h',1,1,6),
  (19,2,'Chaveiro Express',1,2,7),
  (20,3,'Pintura Profissional',1,1,3),
  (20,4,'Jardinagem e Paisagismo',1,2,5);

INSERT INTO recebimento (id_encomenda, valor_pago, data_pagamento)
VALUES
  -- Encomenda Fechada
  (1,  90.00, '2024-01-05'),
  (1,  90.00, '2024-01-15'),
  
  (2, 160.00, '2024-01-08'),
  (2, 160.00, '2024-01-18'),
  
  (3,  47.50, '2024-01-12'),
  (3,  47.50, '2024-01-22'),
 
  (4, 205.00, '2024-01-15'),
  (4, 205.00, '2024-01-25'),
  
  (5,  75.00, '2024-01-20'),
  (5,  75.00, '2024-01-30'),
 
  (6, 137.50, '2024-01-25'),
  (6, 137.50, '2024-02-04'),
 
  (7, 250.00, '2024-02-01'),
  (7, 250.00, '2024-02-11'),
  
  (8,  60.00, '2024-02-05'),
  (8,  60.00, '2024-02-15'),
  
  (9, 170.00, '2024-02-10'),
  (9, 170.00, '2024-02-20'),
  
  (10, 105.00, '2024-02-14'),
  (10, 105.00, '2024-02-24'),

  -- Encomendas 11 a 20: Aberta -> apenas o sinal, restante pendente
  (11,  80.00, '2024-02-18'),
  (12, 145.00, '2024-02-22'),
  (13, 190.00, '2024-02-25'),
  (14,  50.00, '2024-03-01'),
  (15, 225.00, '2024-03-05'),
  (16, 115.00, '2024-03-08'),
  (17,  85.00, '2024-03-12'),
  (18, 155.00, '2024-03-15'),
  (19, 130.00, '2024-03-18'),
  (20,  70.00, '2024-03-22');

  